version: '2'

services:
  postgres:
    image: 'postgres:10.4'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env'

  website:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    env_file:
      - '.env'
volumes:
  postgres: